
language: python

python:
  - "3.5"
  - "3.4"
  - "3.3"
  - "2.7"
  - "2.6"
  - "pypy"
  - "pypy3"

before_install:
  - pip install codecov

install:
  - pip install -r requirements.txt
  - pip install -r test_requirements.txt
  - pip install coverage

after_success:
  - codecov

# command to run tests, e.g. python setup.py test
script: make test
